[package]
name = "mi-presency-api"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version = "0.5.0-rc.2", features = ["json"]}
serde = "1.0.136"
dotenv = "0.15.0"
bson = "1.2"
serde_json = "1.0"

[dependencies.mongodb]
version = "2.8.2"
default-features = false
features = ["sync"] 
